//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Managment_Office
{
    using System;
    using System.Collections.Generic;
    
    public partial class managementByan
    {
        public int ID { get; set; }
        public string byanData { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
        public string ImportPlace { get; set; }
        public Nullable<System.DateTime> DateExport { get; set; }
        public string ExportPlace { get; set; }
        public string user_name { get; set; }
        public string imageSrc { get; set; }
        public Nullable<int> impoertId { get; set; }
        public Nullable<int> exportId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string notices { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string file_type { get; set; }
        public string qta3Name { get; set; }
        public Nullable<int> qta3_ID { get; set; }
        public Nullable<int> folder_id { get; set; }
        public string name_applicant { get; set; }
    }
}
